packages:
  - 'packages/*'

allowBuilds:
  '@bufbuild/buf': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  protobufjs: true

catalog:
  "@types/node": "^24.12.2"
  "dotenv": "^17.4.2"
  "tsx": "^4.21.0"
  "typescript": "^6.0.3"
  "vitest": "^4.1.5"
  "zod": "^4.4.3"
