services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:24
    volumes:
      - ..:/workspace
    working_dir: /workspace
    command: sleep infinity

  db:
    image: postgres:18-alpine
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql
      - ./postgres.sql:/docker-entrypoint-initdb.d/postgres.sql

volumes:
  postgres:
